export const braillePatterns = {
  'a': [true, false, false, false, false, false],
  'b': [true, true, false, false, false, false],
  'c': [true, false, false, true, false, false],
  'd': [true, false, false, true, true, false],
  'e': [true, false, false, false, true, false],
  'f': [true, true, false, true, false, false],
  'g': [true, true, false, true, true, false],
  'h': [true, true, false, false, true, false],
  'i': [false, true, false, true, false, false],
  'j': [false, true, false, true, true, false],
  'k': [true, false, true, false, false, false],
  'l': [true, true, true, false, false, false],
  'm': [true, false, true, true, false, false],
  'n': [true, false, true, true, true, false],
  'o': [true, false, true, false, true, false],
  'p': [true, true, true, true, false, false],
  'q': [true, true, true, true, true, false],
  'r': [true, true, true, false, true, false],
  's': [false, true, true, true, false, false],
  't': [false, true, true, true, true, false],
  'u': [true, false, true, false, false, true],
  'v': [true, true, true, false, false, true],
  'w': [false, true, false, true, true, true],
  'x': [true, false, true, true, false, true],
  'y': [true, false, true, true, true, true],
  'z': [true, false, true, false, true, true],
  // Acentos y Ñ
  'á': [true, false, false, false, false, true],
  'é': [true, true, false, false, false, true],
  'í': [false, false, true, true, false, false],
  'ó': [false, false, true, true, false, true],
  'ú': [true, true, true, false, false, true],
  'ñ': [true, true, false, true, true, true],
  'ü': [true, true, false, false, true, true],
  // Números
  '1': [true, false, false, false, false, false],
  '2': [true, true, false, false, false, false],
  '3': [true, false, false, true, false, false],
  '4': [true, false, false, true, true, false],
  '5': [true, false, false, false, true, false],
  '6': [true, true, false, true, false, false],
  '7': [true, true, false, true, true, false],
  '8': [true, true, false, false, true, false],
  '9': [false, true, false, true, false, false],
  '0': [false, true, false, true, true, false],
  ' ': [false, false, false, false, false, false], // Espacio
  // Puntuación
  '.': [false, true, false, false, true, true],
  ',': [false, true, false, false, false, false],
  '?': [false, true, true, false, false, true],
  '¿': [false, true, false, false, false, true],
  '!': [false, true, true, false, true, false],
  '¡': [false, true, true, false, true, false], 
  // Prefijos
  'number_prefix': [false, false, true, true, true, true],
  'capital_prefix': [false, false, false, false, false, true],
  'blank': [false, false, false, false, false, false],
};